---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: post-sync
  annotations:
    argocd.argoproj.io/hook: PostSync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: post-sync
  annotations:
    argocd.argoproj.io/hook: PostSync
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "update", "get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: post-sync
  annotations:
    argocd.argoproj.io/hook: PostSync
subjects:
  - kind: ServiceAccount
    name: post-sync
roleRef:
  kind: Role
  name: post-sync
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: post-sync
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      serviceAccountName: post-sync
      containers:
        - name: create-configmap
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              export TZ=Europe/Paris
              SUFFIX=$(date +%Y%m%d-%H%M%S)
              kubectl create configmap post-sync-{{ .Values.run }}-$SUFFIX --from-literal=foo=bar --dry-run=client -o yaml | kubectl apply -f -
      restartPolicy: OnFailure
